//spotify-playlists

import React from 'react';
import Heading from '../components/Navbar';

const Article = () => {
  return (
    <>
      <Heading></Heading>
      <h2>Spotify Playlists: A Novel Form of Self-Expression</h2>
      <p>The expiration of a licensing deal between Spotify and Kakao Entertainment in February of 2021 led to the <a href='https://variety.com/2021/digital/news/spotify-k-pop-kakao-licensing-dispute-1234927727/' className='underline text-black'>removal of hundreds of Korean artists’ music worldwide</a>. Instantly, thousands of fans lost not only the music they love but also many of their self-curated Spotify playlists. I personally remember the feeling of scrolling through my 71+ playlists only for them to be completely desolate: a mass of grayed-out files. All those hours spent personalizing my playlists to fit my needs at a moment’s notice—gone. As I reached out to others, there was a consensus about the empty feeling that settled. We were left expressionless.</p>
      <p>As <a href="https://www.bc.edu/content/dam/files/centers/boisi/pdf/s091/Welcome_address_to_freshman_at_Boston_Conservatory.pdf" className='underline text-black'>Dr. Karl Paulnack states</a> in his welcome address to the incoming Boston Conservatory freshman, “Music is one of the ways in which we say, ‘I am alive, and my life has meaning’.” No one can write out emotion; it is physically impossible to put into words something you feel. Music, on the other hand, reveals a range of emotions unique to everyone. Today, numerous streaming platforms, such as Spotify and Apple Music, allow their listeners to not only save the music that is meaningful to them but also provide them with opportunities to <a href="https://support.spotify.com/us/article/create-playlists/" className='underline text-black'>organize their music into self-produced playlists</a>. This allows listeners to arrange their music, regardless of album or artist, in any order based on their emotions, moods, and feelings. <a href="https://journals.sagepub.com/doi/full/10.1177/2056305119847514" className='underline text-black'>A mood can be defined</a> as a state of mind in which you think about everything in context of the present feeling. Thus, playlists serve as a vector of self-expression—a way of making sense of how we feel in a particular moment. Furthermore, the <a href="https://artists.spotify.com/blog/share-new-music-for-playlist-consideration" className='underline text-black'>Spotify algorithm takes advantage</a> of the connection between mood and music to recommend songs and artists to their listeners based on the titles and songs found in their playlists. Spotify states that, “it’s important to give us as much information about the track as possible—genre, mood, and other data points all help us make decisions,” to curate perfect recommendations for their listeners.</p>
      <p>In and of itself, playlist making is creation at its purest form.. From the profile picture you choose, to the title, content, or even the order of the songs, you can build a story, store a profound memory, or pinpoint an explicit mood based on the meaning you give to different songs or genres of music. Playlists can be as specific or broad as it is necessary in the moment of creation. For example, I have one playlist that follows the comprehensive color spectrum: my effort to find a connection between color, sound, and emotion. On the other hand, my “celestial ether” playlist encodes an explicit memory of stargazing at the Mauna Kea summit in Hawaii. In other words, there are no constraints to creating a playlist. They are an avenue through which we can feel—subjective to everyone’s experiences. Moreover, <a href='https://www.journals.uchicago.edu/doi/full/10.1086/681787?casa_token=HleW6c65-T4AAAAA:9EKLrGh1fAELeQ537vMHJ4RdohQSK0b8SDZHyXFXgRPJU5-eF9d4um6l8Qr-W7lNzu-_mhyfT833' className='underline text-black'>music historian Dr. Paul Anderson argues</a> that people have emotional attachments to playlists because there is a need to express our moods, which tends to be hard to do through verbal communication. Playlist creation provides an alternative method of navigating human emotions and plays an important role in regulating mental health.</p>
      <p>Finally, playlists create cultures and communities. Spotify allows listeners to <a href='https://artists.spotify.com/blog/share-new-music-for-playlist-consideration' className='underline text-black'>share their playlists</a> for others to publicly follow them and gain inspiration. Just like people can bond over certain genres of music they enjoy, an intimacy is found in people who follow each other’s playlists. <a href='https://journals.sagepub.com/doi/full/10.1177/2056305119847514' className='underline text-black'>One study takes it a step further</a>, arguing that playlists themselves are “affective genres”—in that they have cultural implications and can be categorized based on the moods and emotions they evoke. Thus, playlists facilitate a feeling of belonging among followers—that their feelings are valid and can be expressed.</p>
      <p>Luckily, Kakao and Spotify reached an agreement in late March of 2021 and all songs returned to the music platform, back in their respective playlists. In this short time, I realized how important playlist creation was to my everyday life. Playlist creation is a way in which we can discover our inner thoughts and feelings without having to stress about explaining ourselves to anyone. Thus, we should take advantage of this mode of self-expression. Ultimately, playlists  can allow us to express ourselves, find meaning in and validate our emotions, and build a community among the public.</p>
    </>
  );
};

export default Article;